# Generated by Django 4.2.5 on 2023-09-29 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_title', models.CharField(max_length=140)),
                ('sub_title', models.CharField(max_length=140)),
                ('theme', models.CharField(choices=[('pro', 'Pro'), ('edu', 'Edu')], max_length=40)),
                ('category', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=40)),
                ('project_summary', models.CharField(max_length=255)),
                ('role', models.PositiveIntegerField()),
                ('sido', models.CharField(max_length=80)),
                ('sigungu', models.CharField(max_length=80)),
                ('address_1', models.CharField(max_length=140)),
                ('address_2', models.CharField(max_length=140)),
                ('site_plan', models.CharField(max_length=40)),
                ('use', models.CharField(max_length=40)),
                ('project_type', models.CharField(max_length=40)),
                ('result', models.CharField(max_length=80)),
                ('design_period', models.CharField(max_length=40)),
                ('construction_period', models.CharField(max_length=40)),
                ('site_area', models.DecimalField(decimal_places=4, max_digits=12)),
                ('coverage_area', models.DecimalField(decimal_places=4, max_digits=12)),
                ('gross_floor_area', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='GFA')),
                ('stories', models.IntegerField()),
                ('project_introduction', models.CharField(max_length=255)),
                ('project_prologue', models.CharField(max_length=255)),
                ('project_site_description', models.CharField(max_length=255)),
                ('project_design_strategy', models.CharField(max_length=255)),
                ('project_analysis', models.CharField(max_length=255)),
                ('design_concept', models.CharField(max_length=255)),
                ('retail_design_strategy', models.CharField(max_length=255)),
                ('amenity_design_strategy', models.CharField(max_length=255)),
                ('unit_planning', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
