# Generated by Django 4.2.5 on 2023-09-29 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='theme',
        ),
        migrations.AddField(
            model_name='work',
            name='kind',
            field=models.CharField(choices=[('real_estate', 'Real Estate'), ('architecture', 'Architecture')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
